# Generated by Django 6.0.3 on 2026-04-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('userpassword', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('mobilenumber', models.CharField(max_length=12)),
                ('alternatemobile', models.CharField(max_length=12)),
            ],
        ),
    ]
