# Generated by Django 6.0.3 on 2026-04-07 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart_user_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
