# Generated by Django 6.0.3 on 2026-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant')], default='shirt', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
